provider: Add more debug and error messages
So that it can print something like this:

$ sudo test/work/zero-ply/src/ply/ply -c true -d 'BEGIN { print("BEGIN\n"); }'
debug: ir_bpf_generate: v0 -> r2
debug: unlimited memlock
debug: writing xprobe: p:ply955335/p43d060_lt-ply_6230 /home/namhyung/project/ply/test/work/zero-ply/src/ply/.libs/lt-ply:6230
error: BEGIN: Unable to create xprobe: Invalid argument
ERR:-22