syscall: fix bpf_map_op for gcc 15 union initialization semantics
Ensure full zero-initialization of union bpf_attr in bpf_map_op to
accommodate gcc 15 changes.

Starting with gcc 15, initializing a union with {} only zeroes the first
member, rather than the entire union [1]. This can lead to uninitialized
fields in bpf_attr, causing errors such as:

    # ply 'kprobe:vfs_read { print(comm); }'
    error: could not link map to queue
    error: unable to create buffer 'stdbuf'
    ERR: -22

Fix this by explicitly zero-initializing bpf_attr with {} before
assigning its members.

Link: https://gcc.gnu.org/gcc-15/changes.html [1]

Signed-off-by: Ze Huang <zehuang@qti.qualcomm.com>